---
title: "Compare Against BayesFactor with 1-RE Term"
output: html_notebook
---

# Prepare Data

```{r, message=FALSE}
data("fhch2010", package = "afex")

library("tidyverse")

fhch <- as_tibble(fhch2010) %>% 
  filter(correct)

fhch2 <- fhch %>% 
  group_by(id, stimulus) %>% 
  nest() %>% 
  mutate(samp = map(data, ~.[1:5,])) %>% 
  select(id, stimulus, samp) %>% 
  unnest()
```

# Example 1
## Compute Bayes Factor with bfrms
```{r, message=FALSE, results='hide'}
library("bfrms")
fit1 <- bfrm(rt ~ task + (1|id), 
             fhch2, 
             iter = 25000, warmup = 1000,
             cores = 4,
             prior_arg = list(r_fixed = 0.5, r_random = 1))
fit01 <- bfrm(rt ~ 1 + (1|id), 
              fhch2, 
              iter = 25000, warmup = 1000,
              cores = 4,
              prior_arg = list(r_fixed = 0.5, r_random = 1))
```

```{r}
bayes_factor(fit1, fit01, silent = TRUE)
```

## Compare to BayesFactor
```{r, message=FALSE}
library("BayesFactor")
mod1 <- lmBF(rt ~ task + id, fhch2, whichRandom = "id", 
             rscaleFixed = 0.5, rscaleRandom = 1)
mod01 <- lmBF(rt ~ 1 + id, fhch2, whichRandom = "id", 
              rscaleFixed = 0.5, rscaleRandom = 1)
mod1 / mod01
```

# Example 2
## Compute Bayes Factor with bfrms
```{r, message=FALSE, results='hide'}
fit2 <- bfrm(rt ~ stimulus + (stimulus||id), 
             fhch2, 
             iter = 25000, warmup = 1000,
             cores = 4,
             prior_arg = list(r_fixed = 0.5, r_random = 1))
fit02 <- bfrm(rt ~ 1 + (stimulus||id), 
              fhch2, 
              iter = 25000, warmup = 1000,
              cores = 4,
              prior_arg = list(r_fixed = 0.5, r_random = 1))
```

```{r}
bayes_factor(fit2, fit02, silent = TRUE)
```

## Compare to BayesFactor
```{r, message=FALSE}
mod2 <- lmBF(rt ~ stimulus + id + stimulus:id, fhch2,
             whichRandom = c("id", "stimulus:id"), 
             rscaleFixed = 0.5, rscaleRandom = 1)
mod02 <- lmBF(rt ~ 1 + id + stimulus:id, fhch2,
              whichRandom = c("id", "stimulus:id"),
              rscaleFixed = 0.5, rscaleRandom = 1)
mod2 / mod02
```

# Example 3
## Compute Bayes Factor with bfrms
```{r, message=FALSE, results='hide'}
fit3 <- bfrm(rt ~ task + stimulus + (stimulus||id), 
             fhch2, 
             iter = 25000, warmup = 1000,
             cores = 4,
             prior_arg = list(r_fixed = 0.5, r_random = 1))
fit03_1 <- bfrm(rt ~ stimulus + (stimulus||id), 
                fhch2, 
                iter = 25000, warmup = 1000,
                cores = 4,
                prior_arg = list(r_fixed = 0.5, r_random = 1))
fit03_2 <- bfrm(rt ~ task + (stimulus||id), 
                fhch2, 
                iter = 25000, warmup = 1000,
                cores = 4,
                prior_arg = list(r_fixed = 0.5, r_random = 1))
```

```{r}
bayes_factor(fit3, fit03_1, silent = TRUE)
bayes_factor(fit3, fit03_2, silent = TRUE)
```

## Compare to BayesFactor
```{r, message=FALSE}
mod3 <- lmBF(rt ~ task +
               stimulus + id + stimulus:id, fhch2,
             whichRandom = c("id", "stimulus:id"), 
             rscaleFixed = 0.5, rscaleRandom = 1)
mod03_1 <- lmBF(rt ~ stimulus + id + stimulus:id, fhch2,
                whichRandom = c("id", "stimulus:id"),
                rscaleFixed = 0.5, rscaleRandom = 1)
mod03_2 <- lmBF(rt ~ task + id + stimulus:id, fhch2,
                whichRandom = c("id", "stimulus:id"),
                rscaleFixed = 0.5, rscaleRandom = 1)
mod3 / mod03_1
mod3 / mod03_2
```

# Example 4
## Compute Bayes Factor with bfrms
```{r, message=FALSE, results='hide'}
fit4 <- bfrm(rt ~ task*stimulus + (stimulus||id), 
             fhch2, 
             iter = 25000, warmup = 1000,
             cores = 4,
             prior_arg = list(r_fixed = 0.5, r_random = 1))
fit04 <- bfrm(rt ~ task + stimulus + (stimulus||id), 
              fhch2, 
              iter = 25000, warmup = 1000,
              cores = 4,
              prior_arg = list(r_fixed = 0.5, r_random = 1))
```

```{r}
bayes_factor(fit4, fit04, silent = TRUE)
```

## Compare to BayesFactor
```{r, message=FALSE}
mod4 <- lmBF(rt ~ task + stimulus + task:stimulus +
               id + stimulus:id, fhch2,
             whichRandom = c("id", "stimulus:id"), 
             rscaleFixed = 0.5, rscaleRandom = 1)
mod04 <- lmBF(rt ~ task + stimulus +
                id + stimulus:id, fhch2,
              whichRandom = c("id", "stimulus:id"), 
              rscaleFixed = 0.5, rscaleRandom = 1)
mod4 / mod04
```
